# ESEMPIO:
# ./pythonscript.sh /opt/IMPORT_CATASTO/PYTHON_WORKSPACE/CXFToShape/src/cxfToShape.py /opt/IMPORT_CATASTO/DATI/ATTUALITA/MANAGE/CATASTO/work/Cassini-Soldner /opt/IMPORT_CATASTO/DATI/ATTUALITA/MANAGE/CATASTO/work/Gauss-Boaga /opt/IMPORT_CATASTO/DATI/ATTUALITA/SHAPEFILE/ u_cat_

export PYTHONPATH=/home/fesposit/Lavoro/git_repository/URBAMID/URBAMID/CXFToShape:/usr/lib64/python3.7:/usr/lib64/python3.7/lib-dynload:/usr/local/lib/python3.7/site-packages:/usr/lib64/python3.7/site-packages:/usr/lib/python3.7/site-packages:/usr/bin/python3.7:/usr/local/lib64/python3.7/site-packages:/usr/share/qgis/python

# NOME DELLO SCRIPT PYTHON DA ESEGUIRE
export PYTHON_SCRIPT_FILE=$1
# DIRECTORY DOVE RISIEDONO I FILE CXF PER I CASSINI SOLDNER
export CASSINI_SOLDNER_DIRECTORY=$2
# DIRECTORY DOVE RISIEDONO I FILE CXF PER I GAUSS BOAGA
export GAUSS_BOAGA_DIRECTORY=$3
# DIRECTORY DOVE VERRANNO SALVATI GLI SHAPEFILE PRODOTTI DALLO SCRIPT PYTHON
export SHAPEFILE_DIRECOTY=$4
# PREFISSO DEGLI SHAPEFILE
export SHAPEFILE_PREFIX=$5

python3.7 $PYTHON_SCRIPT_FILE $CASSINI_SOLDNER_DIRECTORY $GAUSS_BOAGA_DIRECTORY $SHAPEFILE_DIRECOTY $SHAPEFILE_PREFIX

#python3.7 /opt/IMPORT_CATASTO/PYTHON_WORKSPACE/CXFToShape/src/cxfToShape.py /opt/IMPORT_CATASTO/DATI/ATTUALITA/MANAGE/CATASTO/work/Cassini-Soldner /opt/IMPORT_CATASTO/DATI/ATTUALITA/MANAGE/CATASTO/work/Gauss-Boaga /opt/IMPORT_CATASTO/DATI/ATTUALITA/SHAPEFILE/ u_cat_