@echo off
@echo Inizio installazione Plugin Urbamid...
@echo Copia files di configurazione...
XCOPY /s Config %homepath%\Urbamid\Config\ /E/F/Y
if not exist %homepath%\Urbamid\Log mkdir %homepath%\Urbamid\log
@echo Installazione plugin in corso...
START UrbamidAddIn.esriAddIn
@echo Installazione terminata!
